# Generated by Django 3.2 on 2023-07-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0004_auto_20230718_2315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
